// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/hktrib/RetailGo/ent/predicate"
	"github.com/hktrib/RetailGo/ent/usertostore"
)

// UserToStoreDelete is the builder for deleting a UserToStore entity.
type UserToStoreDelete struct {
	config
	hooks    []Hook
	mutation *UserToStoreMutation
}

// Where appends a list predicates to the UserToStoreDelete builder.
func (utsd *UserToStoreDelete) Where(ps ...predicate.UserToStore) *UserToStoreDelete {
	utsd.mutation.Where(ps...)
	return utsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (utsd *UserToStoreDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, utsd.sqlExec, utsd.mutation, utsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (utsd *UserToStoreDelete) ExecX(ctx context.Context) int {
	n, err := utsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (utsd *UserToStoreDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usertostore.Table, nil)
	if ps := utsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, utsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	utsd.mutation.done = true
	return affected, err
}

// UserToStoreDeleteOne is the builder for deleting a single UserToStore entity.
type UserToStoreDeleteOne struct {
	utsd *UserToStoreDelete
}

// Where appends a list predicates to the UserToStoreDelete builder.
func (utsdo *UserToStoreDeleteOne) Where(ps ...predicate.UserToStore) *UserToStoreDeleteOne {
	utsdo.utsd.mutation.Where(ps...)
	return utsdo
}

// Exec executes the deletion query.
func (utsdo *UserToStoreDeleteOne) Exec(ctx context.Context) error {
	n, err := utsdo.utsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usertostore.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (utsdo *UserToStoreDeleteOne) ExecX(ctx context.Context) {
	if err := utsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
