// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// CategoryItem is the predicate function for categoryitem builders.
type CategoryItem func(*sql.Selector)

// ClerkUser_Store is the predicate function for clerkuser_store builders.
type ClerkUser_Store func(*sql.Selector)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// Store is the predicate function for store builders.
type Store func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserToStore is the predicate function for usertostore builders.
type UserToStore func(*sql.Selector)
