// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hktrib/RetailGo/internal/ent/clerkuser_store"
	"github.com/hktrib/RetailGo/internal/ent/predicate"
)

// ClerkUserStoreQuery is the builder for querying ClerkUser_Store entities.
type ClerkUserStoreQuery struct {
	config
	ctx        *QueryContext
	order      []clerkuser_store.OrderOption
	inters     []Interceptor
	predicates []predicate.ClerkUser_Store
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ClerkUserStoreQuery builder.
func (cusq *ClerkUserStoreQuery) Where(ps ...predicate.ClerkUser_Store) *ClerkUserStoreQuery {
	cusq.predicates = append(cusq.predicates, ps...)
	return cusq
}

// Limit the number of records to be returned by this query.
func (cusq *ClerkUserStoreQuery) Limit(limit int) *ClerkUserStoreQuery {
	cusq.ctx.Limit = &limit
	return cusq
}

// Offset to start from.
func (cusq *ClerkUserStoreQuery) Offset(offset int) *ClerkUserStoreQuery {
	cusq.ctx.Offset = &offset
	return cusq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cusq *ClerkUserStoreQuery) Unique(unique bool) *ClerkUserStoreQuery {
	cusq.ctx.Unique = &unique
	return cusq
}

// Order specifies how the records should be ordered.
func (cusq *ClerkUserStoreQuery) Order(o ...clerkuser_store.OrderOption) *ClerkUserStoreQuery {
	cusq.order = append(cusq.order, o...)
	return cusq
}

// First returns the first ClerkUser_Store entity from the query.
// Returns a *NotFoundError when no ClerkUser_Store was found.
func (cusq *ClerkUserStoreQuery) First(ctx context.Context) (*ClerkUser_Store, error) {
	nodes, err := cusq.Limit(1).All(setContextOp(ctx, cusq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{clerkuser_store.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cusq *ClerkUserStoreQuery) FirstX(ctx context.Context) *ClerkUser_Store {
	node, err := cusq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ClerkUser_Store ID from the query.
// Returns a *NotFoundError when no ClerkUser_Store ID was found.
func (cusq *ClerkUserStoreQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cusq.Limit(1).IDs(setContextOp(ctx, cusq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{clerkuser_store.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cusq *ClerkUserStoreQuery) FirstIDX(ctx context.Context) int {
	id, err := cusq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ClerkUser_Store entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ClerkUser_Store entity is found.
// Returns a *NotFoundError when no ClerkUser_Store entities are found.
func (cusq *ClerkUserStoreQuery) Only(ctx context.Context) (*ClerkUser_Store, error) {
	nodes, err := cusq.Limit(2).All(setContextOp(ctx, cusq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{clerkuser_store.Label}
	default:
		return nil, &NotSingularError{clerkuser_store.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cusq *ClerkUserStoreQuery) OnlyX(ctx context.Context) *ClerkUser_Store {
	node, err := cusq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ClerkUser_Store ID in the query.
// Returns a *NotSingularError when more than one ClerkUser_Store ID is found.
// Returns a *NotFoundError when no entities are found.
func (cusq *ClerkUserStoreQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cusq.Limit(2).IDs(setContextOp(ctx, cusq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{clerkuser_store.Label}
	default:
		err = &NotSingularError{clerkuser_store.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cusq *ClerkUserStoreQuery) OnlyIDX(ctx context.Context) int {
	id, err := cusq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ClerkUser_Stores.
func (cusq *ClerkUserStoreQuery) All(ctx context.Context) ([]*ClerkUser_Store, error) {
	ctx = setContextOp(ctx, cusq.ctx, "All")
	if err := cusq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ClerkUser_Store, *ClerkUserStoreQuery]()
	return withInterceptors[[]*ClerkUser_Store](ctx, cusq, qr, cusq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cusq *ClerkUserStoreQuery) AllX(ctx context.Context) []*ClerkUser_Store {
	nodes, err := cusq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ClerkUser_Store IDs.
func (cusq *ClerkUserStoreQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cusq.ctx.Unique == nil && cusq.path != nil {
		cusq.Unique(true)
	}
	ctx = setContextOp(ctx, cusq.ctx, "IDs")
	if err = cusq.Select(clerkuser_store.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cusq *ClerkUserStoreQuery) IDsX(ctx context.Context) []int {
	ids, err := cusq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cusq *ClerkUserStoreQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cusq.ctx, "Count")
	if err := cusq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cusq, querierCount[*ClerkUserStoreQuery](), cusq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cusq *ClerkUserStoreQuery) CountX(ctx context.Context) int {
	count, err := cusq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cusq *ClerkUserStoreQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cusq.ctx, "Exist")
	switch _, err := cusq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cusq *ClerkUserStoreQuery) ExistX(ctx context.Context) bool {
	exist, err := cusq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ClerkUserStoreQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cusq *ClerkUserStoreQuery) Clone() *ClerkUserStoreQuery {
	if cusq == nil {
		return nil
	}
	return &ClerkUserStoreQuery{
		config:     cusq.config,
		ctx:        cusq.ctx.Clone(),
		order:      append([]clerkuser_store.OrderOption{}, cusq.order...),
		inters:     append([]Interceptor{}, cusq.inters...),
		predicates: append([]predicate.ClerkUser_Store{}, cusq.predicates...),
		// clone intermediate query.
		sql:  cusq.sql.Clone(),
		path: cusq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ClerkID string `json:"clerk_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ClerkUserStore.Query().
//		GroupBy(clerkuser_store.FieldClerkID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cusq *ClerkUserStoreQuery) GroupBy(field string, fields ...string) *ClerkUserStoreGroupBy {
	cusq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ClerkUserStoreGroupBy{build: cusq}
	grbuild.flds = &cusq.ctx.Fields
	grbuild.label = clerkuser_store.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ClerkID string `json:"clerk_id,omitempty"`
//	}
//
//	client.ClerkUserStore.Query().
//		Select(clerkuser_store.FieldClerkID).
//		Scan(ctx, &v)
func (cusq *ClerkUserStoreQuery) Select(fields ...string) *ClerkUserStoreSelect {
	cusq.ctx.Fields = append(cusq.ctx.Fields, fields...)
	sbuild := &ClerkUserStoreSelect{ClerkUserStoreQuery: cusq}
	sbuild.label = clerkuser_store.Label
	sbuild.flds, sbuild.scan = &cusq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ClerkUserStoreSelect configured with the given aggregations.
func (cusq *ClerkUserStoreQuery) Aggregate(fns ...AggregateFunc) *ClerkUserStoreSelect {
	return cusq.Select().Aggregate(fns...)
}

func (cusq *ClerkUserStoreQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cusq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cusq); err != nil {
				return err
			}
		}
	}
	for _, f := range cusq.ctx.Fields {
		if !clerkuser_store.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cusq.path != nil {
		prev, err := cusq.path(ctx)
		if err != nil {
			return err
		}
		cusq.sql = prev
	}
	return nil
}

func (cusq *ClerkUserStoreQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ClerkUser_Store, error) {
	var (
		nodes = []*ClerkUser_Store{}
		_spec = cusq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ClerkUser_Store).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ClerkUser_Store{config: cusq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cusq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (cusq *ClerkUserStoreQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cusq.querySpec()
	_spec.Node.Columns = cusq.ctx.Fields
	if len(cusq.ctx.Fields) > 0 {
		_spec.Unique = cusq.ctx.Unique != nil && *cusq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cusq.driver, _spec)
}

func (cusq *ClerkUserStoreQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(clerkuser_store.Table, clerkuser_store.Columns, sqlgraph.NewFieldSpec(clerkuser_store.FieldID, field.TypeInt))
	_spec.From = cusq.sql
	if unique := cusq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cusq.path != nil {
		_spec.Unique = true
	}
	if fields := cusq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, clerkuser_store.FieldID)
		for i := range fields {
			if fields[i] != clerkuser_store.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cusq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cusq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cusq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cusq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cusq *ClerkUserStoreQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cusq.driver.Dialect())
	t1 := builder.Table(clerkuser_store.Table)
	columns := cusq.ctx.Fields
	if len(columns) == 0 {
		columns = clerkuser_store.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cusq.sql != nil {
		selector = cusq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cusq.ctx.Unique != nil && *cusq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cusq.predicates {
		p(selector)
	}
	for _, p := range cusq.order {
		p(selector)
	}
	if offset := cusq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cusq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ClerkUserStoreGroupBy is the group-by builder for ClerkUser_Store entities.
type ClerkUserStoreGroupBy struct {
	selector
	build *ClerkUserStoreQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cusgb *ClerkUserStoreGroupBy) Aggregate(fns ...AggregateFunc) *ClerkUserStoreGroupBy {
	cusgb.fns = append(cusgb.fns, fns...)
	return cusgb
}

// Scan applies the selector query and scans the result into the given value.
func (cusgb *ClerkUserStoreGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cusgb.build.ctx, "GroupBy")
	if err := cusgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ClerkUserStoreQuery, *ClerkUserStoreGroupBy](ctx, cusgb.build, cusgb, cusgb.build.inters, v)
}

func (cusgb *ClerkUserStoreGroupBy) sqlScan(ctx context.Context, root *ClerkUserStoreQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cusgb.fns))
	for _, fn := range cusgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cusgb.flds)+len(cusgb.fns))
		for _, f := range *cusgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cusgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cusgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ClerkUserStoreSelect is the builder for selecting fields of ClerkUserStore entities.
type ClerkUserStoreSelect struct {
	*ClerkUserStoreQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cuss *ClerkUserStoreSelect) Aggregate(fns ...AggregateFunc) *ClerkUserStoreSelect {
	cuss.fns = append(cuss.fns, fns...)
	return cuss
}

// Scan applies the selector query and scans the result into the given value.
func (cuss *ClerkUserStoreSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cuss.ctx, "Select")
	if err := cuss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ClerkUserStoreQuery, *ClerkUserStoreSelect](ctx, cuss.ClerkUserStoreQuery, cuss, cuss.inters, v)
}

func (cuss *ClerkUserStoreSelect) sqlScan(ctx context.Context, root *ClerkUserStoreQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cuss.fns))
	for _, fn := range cuss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cuss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cuss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
