// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one


INSERT into users (
    username, 
    hashed_password, 
    email
) VALUES ($1, $2, $3) RETURNING username, hashed_password, email, password_changed_at, created_at, is_user_verified
`

type CreateUserParams struct {
	Username       string
	HashedPassword string
	Email          string
}

// Checkout the Link for specific on sqlc query commenting for generation!
// https://docs.sqlc.dev/en/stable/tutorials/getting-started-postgresql.html#:~:text=Next%2C%20create%20a%20query.sql%20file%20with%20the%20following
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.HashedPassword, arg.Email)
	var i User
	err := row.Scan(
		&i.Username,
		&i.HashedPassword,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.IsUserVerified,
	)
	return i, err
}
